FIX:[TE-20950]-expand collapse fix
TestsigmaInc/react-inspector pull request #19
Opened 2024-12-17 06:37 UTC by MounikaRadha

### expand collapse functionality  of xml html in rest api

## Jira 
https://testsigma.atlassian.net/browse/TE-20950

### description
- removing the check `if (!expandTree) return;`
- the corresponding change is in https://github.com/TestsigmaInc/groot/tree/fix/TE-20950-expand-collapse-rest-api-fix
- previously when collapse button is pressed -> expandTree=false goes to inspector(in react-inspector)->the previous  code using if clause does not let the tree to collapse
- now here that check is removed 
- but the other affected area is locating element ,there now we are setting expand Tree=true

https://github.com/user-attachments/assets/81f41a4c-afad-448f-afad-4912fe2283a9

2024-12-17 06:56 UTC, jayavel-testsigma submitted a review, later dismissed

2024-12-24 05:45 UTC, NamanAulakh submitted a review, later dismissed

2024-12-25 11:12 UTC, ManoharKrishnaBoppe approved these changes, later dismissed

2024-12-25 12:36 UTC, avi-testsigma requested changes
this is causing performance issue in other use cases. need to dig deeper

2025-01-02 14:24 UTC, closed without merging